name: Orion-LD scan

on:
  schedule:
    # every night at one
    - cron:  '0 1 * * *'
  workflow_dispatch:

env:
  IMAGE: fiware/orion-ld

jobs:
  create-version-matrix:
    runs-on: ubuntu-latest

    steps:

      - id: orion-version
        uses: wistefan/get-releases-by-semver@master
        with:
          include: "PATCH"
          minMinor: "6"
          versionField: "TAG-NAME"
          repository: fiware/context.Orion-LD

    outputs:
      orion-matrix: ${{ steps.orion-version.outputs.releases }}

  vulnerability-scan-snyk:
    needs: create-version-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        orion-version: ${{fromJson(needs.create-version-matrix.outputs.orion-matrix)}}

    steps:

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE }}:${{ matrix.orion-version }}

  vulnerability-scan-clair:
    needs: create-version-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        orion-version: ${{fromJson(needs.create-version-matrix.outputs.orion-matrix)}}

    steps:
      - uses: actions/checkout@v2

      - name: Run compose
        run: |
          wget https://github.com/arminc/clair-scanner/archive/refs/tags/v12.tar.gz
          tar -xvf v12.tar.gz
          ls -l
          cd clair-scanner-12
          ls -l
          chmod +x example-run.sh
          example-run.sh ${{ env.IMAGE }}:${{ matrix.orion-version }}
